window.ReadyPackersLocales = window.ReadyPackersLocales || {};

window.ReadyPackersLocales.es = {
  meta: {
    pageTitle: 'ReadyPackers IoT - Monitor Industrial',
    htmlLang: 'es',
    locale: 'es-CO',
  },
  common: {
    appName: 'ReadyPackers',
    monitorName: 'Monitor IoT',
    emptyDash: '—',
    loading: 'Cargando...',
    errorGeneric: 'Ocurrió un error al procesar la solicitud.',
    noData: 'Sin datos disponibles',
    noSelection: 'Sin selección',
    active: 'Activo',
    inactive: 'Inactivo',
    connected: 'Conectado',
    disconnected: 'Desconectado',
    recentDataMissing: 'Sin datos recientes',
    update: 'Actualizar',
    filter: 'Filtrar',
    save: 'Guardar',
    create: 'Crear',
    cancel: 'Cancelar',
    all: 'Todos',
    yes: 'Sí',
    no: 'No',
    notAvailable: 'N/D',
    approximateLocation: 'Ubicación aproximada',
  },
  language: {
    toggleLabel: 'EN',
    toggleAria: 'Cambiar idioma a inglés',
  },
  public: {
    badge: 'Vista pública',
    loginButton: 'Login',
    title: 'Mapa general de máquinas',
    subtitle: 'Nuestros dispositivos en vivo.',
    panelKicker: 'Cobertura pública',
    panelTitle: 'Monitoreo geográfico aproximado',
    panelNote: 'La ubicación mostrada es aproximada y el zoom está limitado por seguridad.',
    mapLive: 'Cobertura visible',
    mapApproximate: 'Ubicación aproximada',
    approximateBadge: 'Ubicación protegida',
    mapAria: 'Mapa de máquinas registradas',
    loading: 'Cargando máquinas públicas...',
    empty: 'No hay máquinas visibles para mostrar en este momento.',
    summary: 'Se muestran {count} máquinas con ubicación aproximada.',
    loadError: 'No fue posible cargar el mapa público.',
    machineWithoutName: 'Máquina sin nombre',
    machineWithoutDescription: 'Sin descripción',
    ppm: 'Paquetes por minuto',
  },
  auth: {
    title: 'Acceso al Monitor IoT',
    subtitle: 'Inicia sesión con correo electrónico y contraseña.',
    emailLabel: 'Correo electrónico',
    passwordLabel: 'Contraseña',
    loginButton: 'Ingresar',
    loggingIn: 'Ingresando...',
    forgotPassword: 'Olvidé mi contraseña',
    forgotSubmit: 'Solicitar restablecimiento',
    forgotHaveToken: 'Ya tengo un token',
    backToLogin: 'Volver al login',
    resetTokenLabel: 'Token de restablecimiento',
    resetTokenPlaceholder: 'Pega aquí el token',
    resetPasswordLabel: 'Nueva contraseña',
    resetPasswordPlaceholder: 'Nueva contraseña',
    resetSubmit: 'Restablecer contraseña',
    recoveringSession: 'Recuperando sesión...',
    loginRequired: 'Inicia sesión para acceder al monitor.',
    validating: 'Validando credenciales...',
    invalidCredentials: 'Credenciales inválidas.',
    loginError: 'No fue posible iniciar sesión.',
    authRequired: 'Necesitas iniciar sesión para continuar.',
    logoutSuccess: 'La sesión se cerró correctamente.',
    sessionExpired: 'Tu sesión expiró. Inicia sesión nuevamente.',
    sessionAlreadyExpired: 'Tu sesión ya había expirado.',
  },
  nav: {
    telemetry: 'Telemetría',
    audit: 'Auditoría',
    admin: 'Administración',
    logout: 'Cerrar sesión',
  },
  sidebar: {
    deviceId: 'Dispositivo',
    lastUpdate: 'Última actualización',
  },
  telemetry: {
    pageTitle: 'Telemetría',
    pageSubtitle: 'Datos continuos de proceso',
    productsTotal: 'Productos Totales',
    spAverageWeight: 'SP Peso Promedio',
    averageWeight: 'Peso Promedio',
    variable: 'Variable',
    aggregation: 'Agregación',
    seriesTitle: 'Serie temporal',
    points: '{count} puntos',
    inactiveVariables: 'Sin variables registradas',
    aggregatedData: 'Datos agregados',
    timestamp: 'Timestamp',
    average: 'Promedio',
    minimum: 'Mínimo',
    maximum: 'Máximo',
    records: 'N registros',
    selectVariableToLoad: 'Selecciona una variable para cargar datos',
    noDevices: 'Sin dispositivos',
    noVariablesYet: 'Sin variables registradas',
    inactiveValue: 'Inactivo',
    activeDeviceSuffix: 'activo',
    noAvailableData: 'Sin datos disponibles',
    chartRangeLabel: '{label} - {range}',
    datasetAverage: 'Promedio',
    datasetMinimum: 'Mínimo',
    datasetMaximum: 'Máximo',
    timeRange1Min: '1 minuto',
    timeRange5Min: '5 minutos',
    timeRange10Min: '10 minutos',
    timeRange1Hour: '1 hora',
  },
  audit: {
    pageTitle: 'Auditoría',
    pageSubtitle: 'Historial de configuración y alarmas',
    currentConfig: 'Configuración actual de la máquina',
    currentConfigLoading: 'Cargando configuración...',
    noConfig: 'Sin configuración registrada',
    configLoadError: 'Error al cargar configuración',
    eventType: 'Tipo de evento',
    parameter: 'Parámetro',
    limit: 'Límite',
    history: 'Historial de eventos',
    eventsCount: '{count} eventos',
    dateTime: 'Fecha / Hora',
    type: 'Tipo',
    previousValue: 'Valor anterior',
    newValue: 'Valor nuevo',
    detail: 'Detalle',
    eventsLoading: 'Cargando eventos...',
    noEvents: 'Sin eventos registrados',
    eventsLoadError: 'Error al cargar eventos',
    eventTypes: {
      SETPOINT_CHANGE: 'Cambio SetPoint',
      STATE_CHANGE: 'Cambio Estado',
      ALARM_TRIGGER: 'Alarma',
      ALARM_CLEAR: 'Alarma resuelta',
      TARE_ACTION: 'Tara báscula',
      RECIPE_LOAD: 'Cambio receta',
      CALIBRATION: 'Calibración',
    },
    eventBadge: {
      SETPOINT_CHANGE: 'SetPoint',
      STATE_CHANGE: 'Estado',
      ALARM_TRIGGER: 'Alarma',
      ALARM_CLEAR: 'Alarma OK',
      TARE_ACTION: 'Tara',
      RECIPE_LOAD: 'Receta',
      CALIBRATION: 'Calibración',
    },
  },
  admin: {
    pageTitle: 'Administración',
    pageSubtitle: 'Clientes y máquinas',
    clients: 'Clientes',
    machines: 'Máquinas',
    name: 'Nombre',
    email: 'Email',
    initialPassword: 'Contraseña inicial',
    role: 'Rol',
    status: 'Estado',
    action: 'Acción',
    clientRole: 'Cliente',
    statusActive: 'Activo',
    statusInactive: 'Inactivo',
    createClient: 'Crear cliente',
    ownerClient: 'Cliente propietario',
    visibleName: 'Nombre visible',
    machineType: 'Tipo',
    location: 'Ubicación',
    country: 'País',
    internalLocation: 'Ubicación interna de la máquina',
    latitude: 'Latitud',
    longitude: 'Longitud',
    description: 'Descripción',
    createMachine: 'Crear máquina',
    saveMachine: 'Guardar máquina',
    deviceKey: 'deviceKey',
    machineStatusActive: 'Activa',
    machineStatusInactive: 'Inactiva',
    noClients: 'Sin clientes registrados',
    noMachines: 'Sin máquinas registradas',
    noSensors: 'Sin variables registradas para esta máquina',
    selectClient: 'Selecciona cliente',
    plantPlaceholder: 'Planta principal',
    countryPlaceholder: 'Colombia',
    mapHelp: 'Haz clic en el mapa para ubicar el pin. Estas coordenadas son internas.',
    descriptionHelp: 'Usa este campo para notas internas de la máquina. Evita registrar direcciones exactas.',
    usersLoading: 'Cargando...',
    machinesLoading: 'Cargando...',
    actions: {
      activate: 'Activar',
      deactivate: 'Inactivar',
      variables: 'Variables',
      locate: 'Ubicar',
    },
    createClientLoading: 'Creando cliente...',
    createClientSuccess: 'Cliente guardado.',
    createClientError: 'No fue posible crear el cliente.',
    createMachineLoading: 'Creando máquina...',
    saveMachineLoading: 'Guardando máquina...',
    createMachineSuccess: 'Máquina guardada.',
    createMachineError: 'No fue posible crear la máquina.',
    loadAdminError: 'No fue posible cargar administración.',
    completeActionError: 'No fue posible completar la acción.',
    loadingSensors: 'Cargando variables...',
    locateMachineMessage: 'Selecciona la ubicación en el mapa y guarda la máquina.',
    selectMachineSensors: 'Selecciona una máquina para ver variables',
  },
  forms: {
    requiredClientName: 'El nombre del cliente es requerido.',
    requiredClientEmail: 'El email del cliente es requerido.',
    requiredClientPassword: 'La contraseña inicial es requerida.',
    roleNotAllowed: 'Rol no permitido desde esta pantalla.',
    requiredOwner: 'El cliente propietario es requerido.',
    requiredMachineName: 'El nombre de la máquina es requerido.',
    requiredDeviceKey: 'El deviceKey es requerido.',
    invalidLatitude: 'La latitud no es válida.',
    invalidLongitude: 'La longitud no es válida.',
    auditPermissionDenied: 'Permisos insuficientes para auditoría.',
    adminPermissionDenied: 'Permisos insuficientes para administración.',
  },
  footer: {
    copyright: 'ReadyPackers - Sistema de Adquisición de Datos IoT 2026',
  },
};
